version: "3.8"
services:
    db:
        container_name: db
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "vis$$"
        volumes: 
            - /home/ec2-user/mysql-db:/var/lib/mysql
        ports: 
            - 3306:3306